namespace TaskManagement.API.Models.DTO
{
    public class CreateProjectRequestDTO
    {
        // GUID generated by frontend or left empty for DB generation
        public Guid Id { get; set; }
        
        public int ProjectId { get; set; }
        public required string ProjectName { get; set; }
        public required string ProjectGoal { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool IsArchived { get; set; }

        // --- UPDATED TO GUID ---
        // Matches the Project.cs domain model type
        public required Guid CreatedByUserId { get; set; } 
    }
}